name = "marco-vicenzo"
compatibility_date = "2026-09-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "marco-vicenzo-leads"
database_id = "d7c07466-254a-4199-b002-c869553938bc"
